using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CnnData.Lib.BO.ReferenceData
{
  [Table("InputKeys", Schema="Ref")]
  public class InputKey
  {
    [Key]
    [MaxLength(32)]
    public string KeyText { get; set; }

    [Index("IX_InputKeyOrder", 0, IsUnique = true)]
    public int Order { get; set; }

    public static List<InputKey> GetInputKeys()
    {
      return new List<InputKey>()
      {
        new InputKey() { KeyText = "None", Order = 1 },
        new InputKey() { KeyText = "Cancel", Order = 2 },
        new InputKey() { KeyText = "Back", Order = 3 },
        new InputKey() { KeyText = "Tab", Order = 4 },
        new InputKey() { KeyText = "LineFeed", Order = 5 },
        new InputKey() { KeyText = "Clear", Order = 6 },
        new InputKey() { KeyText = "Return", Order = 7 },
        new InputKey() { KeyText = "Enter", Order = 8 },
        new InputKey() { KeyText = "Pause", Order = 9 },
        new InputKey() { KeyText = "Capital", Order = 10 },
        new InputKey() { KeyText = "CapsLock", Order = 11 },
        new InputKey() { KeyText = "KanaMode", Order = 12 },
        new InputKey() { KeyText = "HangulMode", Order = 13 },
        new InputKey() { KeyText = "JunjaMode", Order = 14 },
        new InputKey() { KeyText = "FinalMode", Order = 15 },
        new InputKey() { KeyText = "HanjaMode", Order = 16 },
        new InputKey() { KeyText = "KanjiMode", Order = 17 },
        new InputKey() { KeyText = "Escape", Order = 18 },
        new InputKey() { KeyText = "ImeConvert", Order = 19 },
        new InputKey() { KeyText = "ImeNonConvert", Order = 20 },
        new InputKey() { KeyText = "ImeAccept", Order = 21 },
        new InputKey() { KeyText = "ImeModeChange", Order = 22 },
        new InputKey() { KeyText = "Space", Order = 23 },
        new InputKey() { KeyText = "Prior", Order = 24 },
        new InputKey() { KeyText = "PageUp", Order = 25 },
        new InputKey() { KeyText = "Next", Order = 26 },
        new InputKey() { KeyText = "PageDown", Order = 27 },
        new InputKey() { KeyText = "End", Order = 28 },
        new InputKey() { KeyText = "Home", Order = 29 },
        new InputKey() { KeyText = "Left", Order = 30 },
        new InputKey() { KeyText = "Up", Order = 31 },
        new InputKey() { KeyText = "Right", Order = 32 },
        new InputKey() { KeyText = "Down", Order = 33 },
        new InputKey() { KeyText = "Select", Order = 34 },
        new InputKey() { KeyText = "Print", Order = 35 },
        new InputKey() { KeyText = "Execute", Order = 36 },
        new InputKey() { KeyText = "Snapshot", Order = 37 },
        new InputKey() { KeyText = "PrintScreen", Order = 38 },
        new InputKey() { KeyText = "Insert", Order = 39 },
        new InputKey() { KeyText = "Delete", Order = 40 },
        new InputKey() { KeyText = "Help", Order = 41 },
        new InputKey() { KeyText = "D0", Order = 42 },
        new InputKey() { KeyText = "D1", Order = 43 },
        new InputKey() { KeyText = "D2", Order = 44 },
        new InputKey() { KeyText = "D3", Order = 45 },
        new InputKey() { KeyText = "D4", Order = 46 },
        new InputKey() { KeyText = "D5", Order = 47 },
        new InputKey() { KeyText = "D6", Order = 48 },
        new InputKey() { KeyText = "D7", Order = 49 },
        new InputKey() { KeyText = "D8", Order = 50 },
        new InputKey() { KeyText = "D9", Order = 51 },
        new InputKey() { KeyText = "A", Order = 52 },
        new InputKey() { KeyText = "B", Order = 53 },
        new InputKey() { KeyText = "C", Order = 54 },
        new InputKey() { KeyText = "D", Order = 55 },
        new InputKey() { KeyText = "E", Order = 56 },
        new InputKey() { KeyText = "F", Order = 57 },
        new InputKey() { KeyText = "G", Order = 58 },
        new InputKey() { KeyText = "H", Order = 59 },
        new InputKey() { KeyText = "I", Order = 60 },
        new InputKey() { KeyText = "J", Order = 61 },
        new InputKey() { KeyText = "K", Order = 62 },
        new InputKey() { KeyText = "L", Order = 63 },
        new InputKey() { KeyText = "M", Order = 64 },
        new InputKey() { KeyText = "N", Order = 65 },
        new InputKey() { KeyText = "O", Order = 66 },
        new InputKey() { KeyText = "P", Order = 67 },
        new InputKey() { KeyText = "Q", Order = 68 },
        new InputKey() { KeyText = "R", Order = 69 },
        new InputKey() { KeyText = "S", Order = 70 },
        new InputKey() { KeyText = "T", Order = 71 },
        new InputKey() { KeyText = "U", Order = 72 },
        new InputKey() { KeyText = "V", Order = 73 },
        new InputKey() { KeyText = "W", Order = 74 },
        new InputKey() { KeyText = "X", Order = 75 },
        new InputKey() { KeyText = "Y", Order = 76 },
        new InputKey() { KeyText = "Z", Order = 77 },
        new InputKey() { KeyText = "LWin", Order = 78 },
        new InputKey() { KeyText = "RWin", Order = 79 },
        new InputKey() { KeyText = "Apps", Order = 80 },
        new InputKey() { KeyText = "Sleep", Order = 81 },
        new InputKey() { KeyText = "NumPad0", Order = 82 },
        new InputKey() { KeyText = "NumPad1", Order = 83 },
        new InputKey() { KeyText = "NumPad2", Order = 84 },
        new InputKey() { KeyText = "NumPad3", Order = 85 },
        new InputKey() { KeyText = "NumPad4", Order = 86 },
        new InputKey() { KeyText = "NumPad5", Order = 87 },
        new InputKey() { KeyText = "NumPad6", Order = 88 },
        new InputKey() { KeyText = "NumPad7", Order = 89 },
        new InputKey() { KeyText = "NumPad8", Order = 90 },
        new InputKey() { KeyText = "NumPad9", Order = 91 },
        new InputKey() { KeyText = "Multiply", Order = 92 },
        new InputKey() { KeyText = "Add", Order = 93 },
        new InputKey() { KeyText = "Separator", Order = 94 },
        new InputKey() { KeyText = "Subtract", Order = 95 },
        new InputKey() { KeyText = "Decimal", Order = 96 },
        new InputKey() { KeyText = "Divide", Order = 97 },
        new InputKey() { KeyText = "F1", Order = 98 },
        new InputKey() { KeyText = "F2", Order = 99 },
        new InputKey() { KeyText = "F3", Order = 100 },
        new InputKey() { KeyText = "F4", Order = 101 },
        new InputKey() { KeyText = "F5", Order = 102 },
        new InputKey() { KeyText = "F6", Order = 103 },
        new InputKey() { KeyText = "F7", Order = 104 },
        new InputKey() { KeyText = "F8", Order = 105 },
        new InputKey() { KeyText = "F9", Order = 106 },
        new InputKey() { KeyText = "F10", Order = 107 },
        new InputKey() { KeyText = "F11", Order = 108 },
        new InputKey() { KeyText = "F12", Order = 109 },
        new InputKey() { KeyText = "F13", Order = 110 },
        new InputKey() { KeyText = "F14", Order = 111 },
        new InputKey() { KeyText = "F15", Order = 112 },
        new InputKey() { KeyText = "F16", Order = 113 },
        new InputKey() { KeyText = "F17", Order = 114 },
        new InputKey() { KeyText = "F18", Order = 115 },
        new InputKey() { KeyText = "F19", Order = 116 },
        new InputKey() { KeyText = "F20", Order = 117 },
        new InputKey() { KeyText = "F21", Order = 118 },
        new InputKey() { KeyText = "F22", Order = 119 },
        new InputKey() { KeyText = "F23", Order = 120 },
        new InputKey() { KeyText = "F24", Order = 121 },
        new InputKey() { KeyText = "NumLock", Order = 122 },
        new InputKey() { KeyText = "Scroll", Order = 123 },
        new InputKey() { KeyText = "LeftShift", Order = 124 },
        new InputKey() { KeyText = "RightShift", Order = 125 },
        new InputKey() { KeyText = "LeftCtrl", Order = 126 },
        new InputKey() { KeyText = "RightCtrl", Order = 127 },
        new InputKey() { KeyText = "LeftAlt", Order = 128 },
        new InputKey() { KeyText = "RightAlt", Order = 129 },
        new InputKey() { KeyText = "BrowserBack", Order = 130 },
        new InputKey() { KeyText = "BrowserForward", Order = 131 },
        new InputKey() { KeyText = "BrowserRefresh", Order = 132 },
        new InputKey() { KeyText = "BrowserStop", Order = 133 },
        new InputKey() { KeyText = "BrowserSearch", Order = 134 },
        new InputKey() { KeyText = "BrowserFavorites", Order = 135 },
        new InputKey() { KeyText = "BrowserHome", Order = 136 },
        new InputKey() { KeyText = "VolumeMute", Order = 137 },
        new InputKey() { KeyText = "VolumeDown", Order = 138 },
        new InputKey() { KeyText = "VolumeUp", Order = 139 },
        new InputKey() { KeyText = "MediaNextTrack", Order = 140 },
        new InputKey() { KeyText = "MediaPreviousTrack", Order = 141 },
        new InputKey() { KeyText = "MediaStop", Order = 142 },
        new InputKey() { KeyText = "MediaPlayPause", Order = 143 },
        new InputKey() { KeyText = "LaunchMail", Order = 144 },
        new InputKey() { KeyText = "SelectMedia", Order = 145 },
        new InputKey() { KeyText = "LaunchApplication1", Order = 146 },
        new InputKey() { KeyText = "LaunchApplication2", Order = 147 },
        new InputKey() { KeyText = "Oem1", Order = 148 },
        new InputKey() { KeyText = "OemSemicolon", Order = 149 },
        new InputKey() { KeyText = "OemPlus", Order = 150 },
        new InputKey() { KeyText = "OemComma", Order = 151 },
        new InputKey() { KeyText = "OemMinus", Order = 152 },
        new InputKey() { KeyText = "OemPeriod", Order = 153 },
        new InputKey() { KeyText = "Oem2", Order = 154 },
        new InputKey() { KeyText = "OemQuestion", Order = 155 },
        new InputKey() { KeyText = "Oem3", Order = 156 },
        new InputKey() { KeyText = "OemTilde", Order = 157 },
        new InputKey() { KeyText = "AbntC1", Order = 158 },
        new InputKey() { KeyText = "AbntC2", Order = 159 },
        new InputKey() { KeyText = "Oem4", Order = 160 },
        new InputKey() { KeyText = "OemOpenBrackets", Order = 161 },
        new InputKey() { KeyText = "Oem5", Order = 162 },
        new InputKey() { KeyText = "OemPipe", Order = 163 },
        new InputKey() { KeyText = "Oem6", Order = 164 },
        new InputKey() { KeyText = "OemCloseBrackets", Order = 165 },
        new InputKey() { KeyText = "Oem7", Order = 166 },
        new InputKey() { KeyText = "OemQuotes", Order = 167 },
        new InputKey() { KeyText = "Oem8", Order = 168 },
        new InputKey() { KeyText = "Oem102", Order = 169 },
        new InputKey() { KeyText = "OemBackslash", Order = 170 },
        new InputKey() { KeyText = "ImeProcessed", Order = 171 },
        new InputKey() { KeyText = "System", Order = 172 },
        new InputKey() { KeyText = "OemAttn", Order = 173 },
        new InputKey() { KeyText = "DbeAlphanumeric", Order = 174 },
        new InputKey() { KeyText = "OemFinish", Order = 175 },
        new InputKey() { KeyText = "DbeKatakana", Order = 176 },
        new InputKey() { KeyText = "OemCopy", Order = 177 },
        new InputKey() { KeyText = "DbeHiragana", Order = 178 },
        new InputKey() { KeyText = "OemAuto", Order = 179 },
        new InputKey() { KeyText = "DbeSbcsChar", Order = 180 },
        new InputKey() { KeyText = "OemEnlw", Order = 181 },
        new InputKey() { KeyText = "DbeDbcsChar", Order = 182 },
        new InputKey() { KeyText = "OemBackTab", Order = 183 },
        new InputKey() { KeyText = "DbeRoman", Order = 184 },
        new InputKey() { KeyText = "Attn", Order = 185 },
        new InputKey() { KeyText = "DbeNoRoman", Order = 186 },
        new InputKey() { KeyText = "CrSel", Order = 187 },
        new InputKey() { KeyText = "DbeEnterWordRegisterMode", Order = 188 },
        new InputKey() { KeyText = "ExSel", Order = 189 },
        new InputKey() { KeyText = "DbeEnterImeConfigureMode", Order = 190 },
        new InputKey() { KeyText = "EraseEof", Order = 191 },
        new InputKey() { KeyText = "DbeFlushString", Order = 192 },
        new InputKey() { KeyText = "Play", Order = 193 },
        new InputKey() { KeyText = "DbeCodeInput", Order = 194 },
        new InputKey() { KeyText = "Zoom", Order = 195 },
        new InputKey() { KeyText = "DbeNoCodeInput", Order = 196 },
        new InputKey() { KeyText = "NoName", Order = 197 },
        new InputKey() { KeyText = "DbeDetermineString", Order = 198 },
        new InputKey() { KeyText = "Pa1", Order = 199 },
        new InputKey() { KeyText = "DbeEnterDialogConversionMode", Order = 200 },
        new InputKey() { KeyText = "OemClear", Order = 201 },
        new InputKey() { KeyText = "DeadCharProcessed", Order = 202 }

      };
    }


  }
}
