using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CnnData.Lib.BO.ReferenceData
{
  [Table("WinMediaColors", Schema = "Ref")]
  public class WinMediaColor
  {
    [Key]
    [MaxLength(32)]
    public string ColorText { get; set; }

    [Index("IX_WinMediaColorOrder", 0, IsUnique = true)]
    public int Order { get; set; }

    public static List<WinMediaColor> GetWinMediaColors()
    {
      return new List<WinMediaColor>() {
        new WinMediaColor() { ColorText="AliceBlue", Order=1},
        new WinMediaColor() { ColorText="PaleGoldenrod", Order=2},
        new WinMediaColor() { ColorText="Orchid", Order=3},
        new WinMediaColor() { ColorText="OrangeRed", Order=4},
        new WinMediaColor() { ColorText="Orange", Order=5},
        new WinMediaColor() { ColorText="OliveDrab", Order=6},
        new WinMediaColor() { ColorText="Olive", Order=7},
        new WinMediaColor() { ColorText="OldLace", Order=8},
        new WinMediaColor() { ColorText="Navy", Order=9},
        new WinMediaColor() { ColorText="NavajoWhite", Order=10},
        new WinMediaColor() { ColorText="Moccasin", Order=11},
        new WinMediaColor() { ColorText="MistyRose", Order=12},
        new WinMediaColor() { ColorText="MintCream", Order=13},
        new WinMediaColor() { ColorText="MidnightBlue", Order=14},
        new WinMediaColor() { ColorText="MediumVioletRed", Order=15},
        new WinMediaColor() { ColorText="MediumTurquoise", Order=16},
        new WinMediaColor() { ColorText="MediumSpringGreen", Order=17},
        new WinMediaColor() { ColorText="MediumSlateBlue", Order=18},
        new WinMediaColor() { ColorText="LightSkyBlue", Order=19},
        new WinMediaColor() { ColorText="LightSlateGray", Order=20},
        new WinMediaColor() { ColorText="LightSteelBlue", Order=21},
        new WinMediaColor() { ColorText="LightYellow", Order=22},
        new WinMediaColor() { ColorText="Lime", Order=23},
        new WinMediaColor() { ColorText="LimeGreen", Order=24},
        new WinMediaColor() { ColorText="PaleGreen", Order=25},
        new WinMediaColor() { ColorText="Linen", Order=26},
        new WinMediaColor() { ColorText="Maroon", Order=27},
        new WinMediaColor() { ColorText="MediumAquamarine", Order=28},
        new WinMediaColor() { ColorText="MediumBlue", Order=29},
        new WinMediaColor() { ColorText="MediumOrchid", Order=30},
        new WinMediaColor() { ColorText="MediumPurple", Order=31},
        new WinMediaColor() { ColorText="MediumSeaGreen", Order=32},
        new WinMediaColor() { ColorText="Magenta", Order=33},
        new WinMediaColor() { ColorText="PaleTurquoise", Order=34},
        new WinMediaColor() { ColorText="PaleVioletRed", Order=35},
        new WinMediaColor() { ColorText="PapayaWhip", Order=36},
        new WinMediaColor() { ColorText="SlateGray", Order=37},
        new WinMediaColor() { ColorText="Snow", Order=38},
        new WinMediaColor() { ColorText="SpringGreen", Order=39},
        new WinMediaColor() { ColorText="SteelBlue", Order=40},
        new WinMediaColor() { ColorText="Tan", Order=41},
        new WinMediaColor() { ColorText="Teal", Order=42},
        new WinMediaColor() { ColorText="SlateBlue", Order=43},
        new WinMediaColor() { ColorText="Thistle", Order=44},
        new WinMediaColor() { ColorText="Transparent", Order=45},
        new WinMediaColor() { ColorText="Turquoise", Order=46},
        new WinMediaColor() { ColorText="Violet", Order=47},
        new WinMediaColor() { ColorText="Wheat", Order=48},
        new WinMediaColor() { ColorText="White", Order=49},
        new WinMediaColor() { ColorText="WhiteSmoke", Order=50},
        new WinMediaColor() { ColorText="Tomato", Order=51},
        new WinMediaColor() { ColorText="LightSeaGreen", Order=52},
        new WinMediaColor() { ColorText="SkyBlue", Order=53},
        new WinMediaColor() { ColorText="Sienna", Order=54},
        new WinMediaColor() { ColorText="PeachPuff", Order=55},
        new WinMediaColor() { ColorText="Peru", Order=56},
        new WinMediaColor() { ColorText="Pink", Order=57},
        new WinMediaColor() { ColorText="Plum", Order=58},
        new WinMediaColor() { ColorText="PowderBlue", Order=59},
        new WinMediaColor() { ColorText="Purple", Order=60},
        new WinMediaColor() { ColorText="Silver", Order=61},
        new WinMediaColor() { ColorText="Red", Order=62},
        new WinMediaColor() { ColorText="RoyalBlue", Order=63},
        new WinMediaColor() { ColorText="SaddleBrown", Order=64},
        new WinMediaColor() { ColorText="Salmon", Order=65},
        new WinMediaColor() { ColorText="SandyBrown", Order=66},
        new WinMediaColor() { ColorText="SeaGreen", Order=67},
        new WinMediaColor() { ColorText="SeaShell", Order=68},
        new WinMediaColor() { ColorText="RosyBrown", Order=69},
        new WinMediaColor() { ColorText="Yellow", Order=70},
        new WinMediaColor() { ColorText="LightSalmon", Order=71},
        new WinMediaColor() { ColorText="LightGreen", Order=72},
        new WinMediaColor() { ColorText="DarkRed", Order=73},
        new WinMediaColor() { ColorText="DarkOrchid", Order=74},
        new WinMediaColor() { ColorText="DarkOrange", Order=75},
        new WinMediaColor() { ColorText="DarkOliveGreen", Order=76},
        new WinMediaColor() { ColorText="DarkMagenta", Order=77},
        new WinMediaColor() { ColorText="DarkKhaki", Order=78},
        new WinMediaColor() { ColorText="DarkGreen", Order=79},
        new WinMediaColor() { ColorText="DarkGray", Order=80},
        new WinMediaColor() { ColorText="DarkGoldenrod", Order=81},
        new WinMediaColor() { ColorText="DarkCyan", Order=82},
        new WinMediaColor() { ColorText="DarkBlue", Order=83},
        new WinMediaColor() { ColorText="Cyan", Order=84},
        new WinMediaColor() { ColorText="Crimson", Order=85},
        new WinMediaColor() { ColorText="Cornsilk", Order=86},
        new WinMediaColor() { ColorText="CornflowerBlue", Order=87},
        new WinMediaColor() { ColorText="Coral", Order=88},
        new WinMediaColor() { ColorText="Chocolate", Order=89},
        new WinMediaColor() { ColorText="AntiqueWhite", Order=90},
        new WinMediaColor() { ColorText="Aqua", Order=91},
        new WinMediaColor() { ColorText="Aquamarine", Order=92},
        new WinMediaColor() { ColorText="Azure", Order=93},
        new WinMediaColor() { ColorText="Beige", Order=94},
        new WinMediaColor() { ColorText="Bisque", Order=95},
        new WinMediaColor() { ColorText="DarkSalmon", Order=96},
        new WinMediaColor() { ColorText="Black", Order=97},
        new WinMediaColor() { ColorText="Blue", Order=98},
        new WinMediaColor() { ColorText="BlueViolet", Order=99},
        new WinMediaColor() { ColorText="Brown", Order=100},
        new WinMediaColor() { ColorText="BurlyWood", Order=101},
        new WinMediaColor() { ColorText="CadetBlue", Order=102},
        new WinMediaColor() { ColorText="Chartreuse", Order=103},
        new WinMediaColor() { ColorText="BlanchedAlmond", Order=104},
        new WinMediaColor() { ColorText="DarkSeaGreen", Order=105},
        new WinMediaColor() { ColorText="DarkSlateBlue", Order=106},
        new WinMediaColor() { ColorText="DarkSlateGray", Order=107},
        new WinMediaColor() { ColorText="HotPink", Order=108},
        new WinMediaColor() { ColorText="IndianRed", Order=109},
        new WinMediaColor() { ColorText="Indigo", Order=110},
        new WinMediaColor() { ColorText="Ivory", Order=111},
        new WinMediaColor() { ColorText="Khaki", Order=112},
        new WinMediaColor() { ColorText="Lavender", Order=113},
        new WinMediaColor() { ColorText="Honeydew", Order=114},
        new WinMediaColor() { ColorText="LavenderBlush", Order=115},
        new WinMediaColor() { ColorText="LemonChiffon", Order=116},
        new WinMediaColor() { ColorText="LightBlue", Order=117},
        new WinMediaColor() { ColorText="LightCoral", Order=118},
        new WinMediaColor() { ColorText="LightCyan", Order=119},
        new WinMediaColor() { ColorText="LightGoldenrodYellow", Order=120},
        new WinMediaColor() { ColorText="LightGray", Order=121},
        new WinMediaColor() { ColorText="LawnGreen", Order=122},
        new WinMediaColor() { ColorText="LightPink", Order=123},
        new WinMediaColor() { ColorText="GreenYellow", Order=124},
        new WinMediaColor() { ColorText="Gray", Order=125},
        new WinMediaColor() { ColorText="DarkTurquoise", Order=126},
        new WinMediaColor() { ColorText="DarkViolet", Order=127},
        new WinMediaColor() { ColorText="DeepPink", Order=128},
        new WinMediaColor() { ColorText="DeepSkyBlue", Order=129},
        new WinMediaColor() { ColorText="DimGray", Order=130},
        new WinMediaColor() { ColorText="DodgerBlue", Order=131},
        new WinMediaColor() { ColorText="Green", Order=132},
        new WinMediaColor() { ColorText="Firebrick", Order=133},
        new WinMediaColor() { ColorText="ForestGreen", Order=134},
        new WinMediaColor() { ColorText="Fuchsia", Order=135},
        new WinMediaColor() { ColorText="Gainsboro", Order=136},
        new WinMediaColor() { ColorText="GhostWhite", Order=137},
        new WinMediaColor() { ColorText="Gold", Order=138},
        new WinMediaColor() { ColorText="Goldenrod", Order=139},
        new WinMediaColor() { ColorText="FloralWhite", Order=140},
        new WinMediaColor() { ColorText="YellowGreen", Order=141}
      };
    }
  }
}
