// <auto-generated />
namespace CnnData.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InputKeys_NO_CODE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InputKeys_NO_CODE));
        
        string IMigrationMetadata.Id
        {
            get { return "201710132102054_InputKeys_NO_CODE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
